CXX = g++
CXXFLAGS = -std=c++0x
OBJS = FibNR.o FibR.o Main.o
SRCS = FibNR.cpp FibR.cpp Main.cpp
HEADERS = FibNR.h FibR.h

LabN: 
	g++ FibNR.cpp FibR.cpp Main.cpp -o LabN

LabR: 
	g++ FibR.cpp FibNR.cpp Main.cpp -o LabR

clean:
	rm -f *.o Lab8
